const QUESTIONS = {
  'p2-opinion': [
    { text: "Do you think students should take part in volunteer activities in their community?", wordMin: 50, wordMax: 60 },
    { text: "Do you think it is a good idea for high school students to have part-time jobs?", wordMin: 50, wordMax: 60 },
    { text: "Do you think students should use digital devices instead of paper textbooks at school?", wordMin: 50, wordMax: 60 },
    { text: "Do you think the government should make recycling mandatory for all households?", wordMin: 50, wordMax: 60 },
    { text: "Do you think schools should give students more homework?", wordMin: 50, wordMax: 60 },
    { text: "Do you think it is good for children to have pets at home?", wordMin: 50, wordMax: 60 },
    { text: "Do you think it is a good idea for students to study abroad?", wordMin: 50, wordMax: 60 },
    { text: "Do you think companies should allow their employees to work from home?", wordMin: 50, wordMax: 60 },
    { text: "Do you think online shopping will eventually replace traditional stores in the future?", wordMin: 50, wordMax: 60 },
    { text: "Do you think children should learn about money management at school?", wordMin: 50, wordMax: 60 },
    { text: "Do you think it is important for students to learn how to cook?", wordMin: 50, wordMax: 60 },
    { text: "Do you think all schools should provide a free school lunch program for students?", wordMin: 50, wordMax: 60 },
    { text: "Do you think schools should teach students more about healthy eating habits?", wordMin: 50, wordMax: 60 },
    { text: "Do you think people should reduce the amount of meat they eat?", wordMin: 50, wordMax: 60 },
    { text: "Do you think there should be more parks and green spaces in cities?", wordMin: 50, wordMax: 60 },
    { text: "Do you think it is important for students to participate in club activities at school?", wordMin: 50, wordMax: 60 },
    { text: "Do you think people should use bicycles more instead of cars?", wordMin: 50, wordMax: 60 },
    { text: "Do you think it is a good idea for students to bring their own smartphones to school?", wordMin: 50, wordMax: 60 },
    { text: "Do you think children should help more with household chores at home?", wordMin: 50, wordMax: 60 },
    { text: "Do you think it is better for students to study in groups or to study alone?", wordMin: 50, wordMax: 60 },
    { text: "Do you think all people should have access to free Internet services?", wordMin: 50, wordMax: 60 },
    { text: "Do you think it is a good idea for students to learn about other countries' cultures at school?", wordMin: 50, wordMax: 60 },
    { text: "Do you think there should be more bicycle lanes on roads in Japan?", wordMin: 50, wordMax: 60 },
    { text: "Do you think local governments should build more sports facilities to encourage people to exercise?", wordMin: 50, wordMax: 60 },
    { text: "Do you think schools should teach students more about environmental issues?", wordMin: 50, wordMax: 60 },
    { text: "Do you think it is good for high school students to choose their own school subjects?", wordMin: 50, wordMax: 60 },
    { text: "Do you think companies should give employees more paid holidays to improve their mental health?", wordMin: 50, wordMax: 60 },
    { text: "Do you think it is a good idea for students to keep a diary written in English?", wordMin: 50, wordMax: 60 },
    { text: "Do you think more people should use public transportation instead of driving cars?", wordMin: 50, wordMax: 60 },
    { text: "Do you think it is good for students to discuss their opinions about current news with their classmates?", wordMin: 50, wordMax: 60 },
  ],
  'p2-email': [
    { from: "Alex", body: "Hi!<br><br>I went to <u>a farmers' market</u> in my town last Saturday. It was held near the station and had many stalls selling vegetables and fruits. Many people were shopping there. There was also a small cooking show.<br><br>Do you think farmers' markets will become more popular in cities?<br><br>Your friend,<br>Alex", wordMin: 40, wordMax: 50 },
    { from: "Alex", body: "Hi!<br><br>I visited <u>a science museum</u> downtown last weekend. It was large and had many interesting exhibits. I learned about space and technology. There was a room where visitors could try simple experiments.<br><br>Do you think science museums will attract more young people?<br><br>Your friend,<br>Alex", wordMin: 40, wordMax: 50 },
    { from: "Alex", body: "Hi!<br><br>I joined <u>a cooking class</u> at a community center last week. The teacher showed us how to make simple dishes. The class was small, and everyone enjoyed cooking together. There was a short time to taste the food at the end.<br><br>Do you think cooking classes are useful for students?<br><br>Your friend,<br>Alex", wordMin: 40, wordMax: 50 },
    { from: "Alex", body: "Hi!<br><br>I went to <u>a music festival</u> near the river last weekend. Many people came to enjoy the music, and there were several stages. I listened to different kinds of songs. There was a space where people could relax and eat.<br><br>Do you think music festivals are popular among young people?<br><br>Your friend,<br>Alex", wordMin: 40, wordMax: 50 },
    { from: "Alex", body: "Hi!<br><br>I visited <u>a botanical garden</u> on the weekend. There were many plants from different countries, and it was very quiet. I walked around for a long time. There was a small shop selling plants.<br><br>Do you think botanical gardens are good places to relax?<br><br>Your friend,<br>Alex", wordMin: 40, wordMax: 50 },
    { from: "Alex", body: "Hi!<br><br>I went to <u>a craft fair</u> last Sunday. Many people were selling handmade items such as bags and cups. It was very interesting. There was a corner where people could try making small crafts.<br><br>Do you think craft fairs are popular in local areas?<br><br>Your friend,<br>Alex", wordMin: 40, wordMax: 50 },
    { from: "Alex", body: "Hi!<br><br>I went to <u>a theater</u> in the city last Friday. It was my first time there. The show was very exciting. There was a screen that showed subtitles during the play.<br><br>Do you think theaters will use more technology in the future?<br><br>Your friend,<br>Alex", wordMin: 40, wordMax: 50 },
    { from: "Alex", body: "Hi!<br><br>I went to <u>a food truck event</u> at a park last weekend. There were many trucks selling different kinds of food. The place was very lively. There was live music during the event.<br><br>Do you think food events will become more popular?<br><br>Your friend,<br>Alex", wordMin: 40, wordMax: 50 },
    { from: "Alex", body: "Hi!<br><br>I visited <u>an art gallery</u> near the station last Sunday. There were many paintings and photos. I liked the colorful ones. There was a small space where artists talked about their work.<br><br>Do you think art galleries are interesting for students?<br><br>Your friend,<br>Alex", wordMin: 40, wordMax: 50 },
    { from: "Alex", body: "Hi!<br><br>I went to <u>a flea market</u> last Saturday. Many people were selling old clothes and books. I found some interesting items. There was a place where people could exchange things for free.<br><br>Do you think flea markets are useful?<br><br>Your friend,<br>Alex", wordMin: 40, wordMax: 50 },
    { from: "Alex", body: "Hi!<br><br>I tried <u>a yoga class</u> at a gym yesterday. It was my first time, so I was nervous. The teacher was very kind. There was soft music during the class.<br><br>Do you think yoga classes are good for health?<br><br>Your friend,<br>Alex", wordMin: 40, wordMax: 50 },
    { from: "Alex", body: "Hi!<br><br>I went to <u>a nature park</u> outside the city. There were many trees and animals. It was very peaceful. There were signs to help people learn about nature.<br><br>Do you think nature parks are important?<br><br>Your friend,<br>Alex", wordMin: 40, wordMax: 50 },
    { from: "Alex", body: "Hi!<br><br>I visited <u>a book fair</u> last weekend. Many books were displayed there. I saw many new titles. There was a reading area for children.<br><br>Do you think book fairs will continue to be popular?<br><br>Your friend,<br>Alex", wordMin: 40, wordMax: 50 },
    { from: "Alex", body: "Hi!<br><br>I joined <u>a community garden</u> project. People worked together to grow vegetables. It was very fun. There was a schedule to take care of the plants.<br><br>Do you think community gardens are useful?<br><br>Your friend,<br>Alex", wordMin: 40, wordMax: 50 },
    { from: "Alex", body: "Hi!<br><br>I started studying at <u>a language school</u> last week. The class was small, and the teacher was helpful. I practiced speaking a lot. There was an app to study at home.<br><br>Do you think language schools will use more digital tools?<br><br>Your friend,<br>Alex", wordMin: 40, wordMax: 50 },
    { from: "Alex", body: "Hi!<br><br>I went to <u>a night market</u> last Saturday. There were many food stalls and lights. It was very lively. There was a bus service for people at night.<br><br>Do you think night markets are popular?<br><br>Your friend,<br>Alex", wordMin: 40, wordMax: 50 },
    { from: "Alex", body: "Hi!<br><br>I attended <u>a pottery workshop</u> last weekend. I made a small cup. It was difficult but fun. There was a guide to help beginners.<br><br>Do you think workshops are good for learning skills?<br><br>Your friend,<br>Alex", wordMin: 40, wordMax: 50 },
    { from: "Alex", body: "Hi!<br><br>I visited <u>a climbing gym</u> with my brother. There were many routes for beginners. It was exciting. There was a safety lesson before climbing.<br><br>Do you think climbing gyms will become popular?<br><br>Your friend,<br>Alex", wordMin: 40, wordMax: 50 },
    { from: "Alex", body: "Hi!<br><br>I went to <u>an aquarium</u> near the sea. There were many fish and sea animals. I enjoyed the visit. There was a long tunnel under the water.<br><br>Do you think aquariums are good for learning?<br><br>Your friend,<br>Alex", wordMin: 40, wordMax: 50 },
    { from: "Alex", body: "Hi!<br><br>I tried <u>a cycling trail</u> along a river. The view was beautiful. Many people were riding there. There were rest areas along the trail.<br><br>Do you think cycling trails are useful?<br><br>Your friend,<br>Alex", wordMin: 40, wordMax: 50 },
    { from: "Alex", body: "Hi!<br><br>I found <u>a pop-up store</u> near the station. It was open for a short time. Many young designers were selling items. There was a space to watch them work.<br><br>Do you think pop-up stores will increase?<br><br>Your friend,<br>Alex", wordMin: 40, wordMax: 50 },
    { from: "Alex", body: "Hi!<br><br>I went to <u>a flower market</u> in the morning. There were many colorful flowers. The smell was very nice. There was a service to make your own bouquet.<br><br>Do you think flower markets are popular?<br><br>Your friend,<br>Alex", wordMin: 40, wordMax: 50 },
    { from: "Alex", body: "Hi!<br><br>I visited <u>a photo exhibition</u>. There were many pictures of daily life. I liked them. There was a place to vote for your favorite photo.<br><br>Do you think photo exhibitions are interesting?<br><br>Your friend,<br>Alex", wordMin: 40, wordMax: 50 },
    { from: "Alex", body: "Hi!<br><br>I went to <u>a vintage market</u>. Many old items were sold there. It was interesting. There were stories about the items.<br><br>Do you think vintage markets are popular?<br><br>Your friend,<br>Alex", wordMin: 40, wordMax: 50 },
    { from: "Alex", body: "Hi!<br><br>I stayed at <u>a campsite</u> in the mountains. It was quiet and beautiful. We stayed two nights. There were clean shower facilities.<br><br>Do you think camping is popular?<br><br>Your friend,<br>Alex", wordMin: 40, wordMax: 50 },
    { from: "Alex", body: "Hi!<br><br>I went to <u>a rooftop restaurant</u> in the city. The view was amazing. The food was good. There was a small garden.<br><br>Do you think rooftop restaurants are popular?<br><br>Your friend,<br>Alex", wordMin: 40, wordMax: 50 },
    { from: "Alex", body: "Hi!<br><br>I visited <u>a hot spring resort</u>. The water was warm and relaxing. The view was beautiful. There were outdoor baths.<br><br>Do you think hot spring resorts are popular?<br><br>Your friend,<br>Alex", wordMin: 40, wordMax: 50 },
    { from: "Alex", body: "Hi!<br><br>I went to <u>a board game café</u> with my friends. There were many games to play. It was fun. There was a room for groups.<br><br>Do you think board game cafés will become popular?<br><br>Your friend,<br>Alex", wordMin: 40, wordMax: 50 },
    { from: "Alex", body: "Hi!<br><br>I visited <u>a planetarium</u>. The show was about stars and space. It was very interesting. There were seats to watch the sky.<br><br>Do you think planetariums are useful?<br><br>Your friend,<br>Alex", wordMin: 40, wordMax: 50 },
    { from: "Alex", body: "Hi!<br><br>I went to <u>an ice skating rink</u>. It was inside a mall. Many people were skating. There were lessons for beginners.<br><br>Do you think skating rinks will become popular?<br><br>Your friend,<br>Alex", wordMin: 40, wordMax: 50 },
  ],
  '3-opinion': [
    { text: "What is your favorite place to do your homework?", wordMin: 25, wordMax: 35 },
    { text: "Where do you want to go for your next vacation?", wordMin: 25, wordMax: 35 },
    { text: "What sport do you most enjoy playing?", wordMin: 25, wordMax: 35 },
    { text: "What is your favorite thing to do with your family on holidays?", wordMin: 25, wordMax: 35 },
    { text: "Where would you like to go on your next school trip?", wordMin: 25, wordMax: 35 },
    { text: "What subject do you enjoy studying the most at school?", wordMin: 25, wordMax: 35 },
    { text: "What is your favorite food to eat on a cold day?", wordMin: 25, wordMax: 35 },
    { text: "Where do you like to go when you want to relax?", wordMin: 25, wordMax: 35 },
    { text: "What do you want to be when you grow up?", wordMin: 25, wordMax: 35 },
    { text: "What is your favorite memory from this school year?", wordMin: 25, wordMax: 35 },
    { text: "Where do you want to go for your birthday this year?", wordMin: 25, wordMax: 35 },
    { text: "What new activity do you want to try this summer?", wordMin: 25, wordMax: 35 },
    { text: "What kind of book or manga do you enjoy reading most?", wordMin: 25, wordMax: 35 },
    { text: "Where does your family usually go on long weekends?", wordMin: 25, wordMax: 35 },
    { text: "What kind of movie do you enjoy watching most?", wordMin: 25, wordMax: 35 },
    { text: "Where is the best place to study outside your home?", wordMin: 25, wordMax: 35 },
    { text: "What do you enjoy doing most on a rainy afternoon?", wordMin: 25, wordMax: 35 },
    { text: "What sport do you most enjoy watching?", wordMin: 25, wordMax: 35 },
    { text: "Where do you most want to visit in Japan?", wordMin: 25, wordMax: 35 },
    { text: "What is your favorite home-cooked meal?", wordMin: 25, wordMax: 35 },
    { text: "What club activity do you most enjoy at school?", wordMin: 25, wordMax: 35 },
    { text: "Where do you want to travel when you finish junior high school?", wordMin: 25, wordMax: 35 },
    { text: "What is the best thing about living in your town?", wordMin: 25, wordMax: 35 },
    { text: "What do you do first when you get home from school?", wordMin: 25, wordMax: 35 },
    { text: "What is your favorite thing to do during the school holidays?", wordMin: 25, wordMax: 35 },
    { text: "Where do you like to go shopping with your friends?", wordMin: 25, wordMax: 35 },
    { text: "What hobby would you most like to try in the future?", wordMin: 25, wordMax: 35 },
    { text: "Where is your favorite place to eat out with your family?", wordMin: 25, wordMax: 35 },
    { text: "What do you like to do to cheer yourself up when you are tired?", wordMin: 25, wordMax: 35 },
    { text: "Where is the most beautiful place you have ever visited?", wordMin: 25, wordMax: 35 },
  ],
  '3-email': [
    { from: "James", body: "Hi,<br><br>Thank you for your e-mail.<br>I played in a sports tournament at school last weekend. It was exciting.<br><br><u>What sport did you play?</u> <u>And how many teams joined?</u><br><br>Your friend,<br>James", wordMin: 15, wordMax: 25 },
    { from: "James", body: "Hi,<br><br>Thank you for your e-mail.<br>I went to a zoo with my family. We saw many animals.<br><br><u>How many animals did you see?</u> <u>And how long did you stay?</u><br><br>Your friend,<br>James", wordMin: 15, wordMax: 25 },
    { from: "James", body: "Hi,<br><br>I went camping last month. We stayed near a river and cooked outside. It was fun.<br><br><u>Where did you go camping?</u> <u>And how many days did you stay?</u><br><br>Your friend,<br>James", wordMin: 15, wordMax: 25 },
    { from: "James", body: "Hi,<br><br>Thank you for your e-mail.<br>I started karate lessons. The class is small and the teacher is kind.<br><br><u>How many students are in your class?</u> <u>And how long is each lesson?</u><br><br>Your friend,<br>James", wordMin: 15, wordMax: 25 },
    { from: "James", body: "Hi,<br><br>Thank you for your e-mail.<br>My class performed a school play. Many students came to watch.<br><br><u>How many students performed?</u> <u>And how long was the show?</u><br><br>Your friend,<br>James", wordMin: 15, wordMax: 25 },
    { from: "James", body: "Hi,<br><br>I went to a concert last weekend. The music was great and many songs were played.<br><br><u>Who performed?</u> <u>And how many songs did they sing?</u><br><br>Your friend,<br>James", wordMin: 15, wordMax: 25 },
    { from: "James", body: "Hi,<br><br>Thank you for your e-mail.<br>I joined a new club. It is fun and I made new friends.<br><br><u>What is the name of your club?</u> <u>And how many members are there?</u><br><br>Your friend,<br>James", wordMin: 15, wordMax: 25 },
    { from: "James", body: "Hi,<br><br>Thank you for your e-mail.<br>I had a birthday party. Many friends came and we played games.<br><br><u>How many friends came?</u> <u>And what time did it start?</u><br><br>Your friend,<br>James", wordMin: 15, wordMax: 25 },
    { from: "James", body: "Hi,<br><br>I joined a running race. It was hard but fun. Many students joined.<br><br><u>How long was the race?</u> <u>And how long did it take?</u><br><br>Your friend,<br>James", wordMin: 15, wordMax: 25 },
    { from: "James", body: "Hi,<br><br>Thank you for your e-mail.<br>I cooked dinner for my family. Everyone liked it.<br><br><u>What did you cook?</u> <u>And how long did it take?</u><br><br>Your friend,<br>James", wordMin: 15, wordMax: 25 },
    { from: "James", body: "Hi,<br><br>Thank you for your e-mail.<br>I baked cookies at home. They were sweet and delicious.<br><br><u>What did you bake?</u> <u>And how many did you make?</u><br><br>Your friend,<br>James", wordMin: 15, wordMax: 25 },
    { from: "James", body: "Hi,<br><br>I watched a soccer game. It was very exciting and my team won.<br><br><u>Which teams played?</u> <u>And what was the score?</u><br><br>Your friend,<br>James", wordMin: 15, wordMax: 25 },
    { from: "James", body: "Hi,<br><br>Thank you for your e-mail.<br>I visited a science museum. It had many interesting things.<br><br><u>How many floors did it have?</u> <u>And how long did you stay?</u><br><br>Your friend,<br>James", wordMin: 15, wordMax: 25 },
    { from: "James", body: "Hi,<br><br>Thank you for your e-mail.<br>I got a new pet. It is small and very cute.<br><br><u>What kind of pet is it?</u> <u>And how old is it?</u><br><br>Your friend,<br>James", wordMin: 15, wordMax: 25 },
    { from: "James", body: "Hi,<br><br>I visited my grandparents last weekend. We had a good time together.<br><br><u>How far is it?</u> <u>And how many nights did you stay?</u><br><br>Your friend,<br>James", wordMin: 15, wordMax: 25 },
    { from: "James", body: "Hi,<br><br>Thank you for your e-mail.<br>I went shopping at a mall. I bought some clothes.<br><br><u>What did you buy?</u> <u>And how much did it cost?</u><br><br>Your friend,<br>James", wordMin: 15, wordMax: 25 },
    { from: "James", body: "Hi,<br><br>Thank you for your e-mail.<br>My class went on a field trip. We visited a park.<br><br><u>How many students went?</u> <u>And how did you get there?</u><br><br>Your friend,<br>James", wordMin: 15, wordMax: 25 },
    { from: "James", body: "Hi,<br><br>I started a new hobby. I do it after school and enjoy it.<br><br><u>What is your hobby?</u> <u>And how often do you do it?</u><br><br>Your friend,<br>James", wordMin: 15, wordMax: 25 },
    { from: "James", body: "Hi,<br><br>Thank you for your e-mail.<br>I went to a summer festival. There were many food stalls.<br><br><u>What food did you eat?</u> <u>And what time did you arrive?</u><br><br>Your friend,<br>James", wordMin: 15, wordMax: 25 },
    { from: "James", body: "Hi,<br><br>Thank you for your e-mail.<br>I went to a theme park. I rode many attractions.<br><br><u>How many rides did you go on?</u> <u>And how long did you wait?</u><br><br>Your friend,<br>James", wordMin: 15, wordMax: 25 },
    { from: "James", body: "Hi,<br><br>I started swimming lessons. The class is fun and I go every week.<br><br><u>How many people are there?</u> <u>And how long is each lesson?</u><br><br>Your friend,<br>James", wordMin: 15, wordMax: 25 },
    { from: "James", body: "Hi,<br><br>Thank you for your e-mail.<br>I gave a presentation at school. I practiced a lot.<br><br><u>What was your topic?</u> <u>And how long did it take?</u><br><br>Your friend,<br>James", wordMin: 15, wordMax: 25 },
    { from: "James", body: "Hi,<br><br>Thank you for your e-mail.<br>I went hiking with my family. The trail was beautiful.<br><br><u>How long was the trail?</u> <u>And how many people went?</u><br><br>Your friend,<br>James", wordMin: 15, wordMax: 25 },
    { from: "James", body: "Hi,<br><br>I saw a fireworks show. It was very beautiful and many people watched it.<br><br><u>How many fireworks did you see?</u> <u>And how long did it last?</u><br><br>Your friend,<br>James", wordMin: 15, wordMax: 25 },
    { from: "James", body: "Hi,<br><br>Thank you for your e-mail.<br>I played in a school band. We practiced a lot.<br><br><u>What kind of music did you play?</u> <u>And how many people were in your group?</u><br><br>Your friend,<br>James", wordMin: 15, wordMax: 25 },
    { from: "James", body: "Hi,<br><br>Thank you for your e-mail.<br>I made something in a pottery class. It was fun but difficult.<br><br><u>What did you make?</u> <u>And how long did it take?</u><br><br>Your friend,<br>James", wordMin: 15, wordMax: 25 },
    { from: "James", body: "Hi,<br><br>I went to a baseball game. It was exciting and many people were there.<br><br><u>Which teams played?</u> <u>And how many people were there?</u><br><br>Your friend,<br>James", wordMin: 15, wordMax: 25 },
    { from: "James", body: "Hi,<br><br>Thank you for your e-mail.<br>I had a sleepover with my friends. We talked a lot.<br><br><u>How many friends came?</u> <u>And what time did you go to sleep?</u><br><br>Your friend,<br>James", wordMin: 15, wordMax: 25 },
    { from: "James", body: "Hi,<br><br>Thank you for your e-mail.<br>I went on a cycling trip. It was long but fun.<br><br><u>How far did you go?</u> <u>And how long did it take?</u><br><br>Your friend,<br>James", wordMin: 15, wordMax: 25 },
    { from: "James", body: "Hi,<br><br>I learned a traditional craft. It was interesting and a little difficult.<br><br><u>What did you make?</u> <u>And how long did it take?</u><br><br>Your friend,<br>James", wordMin: 15, wordMax: 25 },
  ],
};
